#ifndef _SERVER_CONFIG_H_
#define _SERVER_CONFIG_H_

#include <stdint.h>

// Memory map
#ifdef __arm__
static const uint32_t SLCR_OFFSET = 0xf8000000,
	CFG_OFFSET = 0x40000000,
	STS_OFFSET = 0x40001000,
	GRADIENT_MEMORY_X_OFFSET = 0x40002000,
	GRADIENT_MEMORY_Y_OFFSET = 0x40004000,
	GRADIENT_MEMORY_Z_OFFSET = 0x40006000,
	GRADIENT_MEMORY_Z2_OFFSET = 0x40008000,	
	RX_DATA_OFFSET = 0x40010000,
	TX_DATA_OFFSET = 0x40020000,
	MICRO_SEQ_MEMORY_OFFSET = 0x40030000,
	MICRO_SEQ_CONFIG_OFFSET = 0x40040000,
	ATTEN_OFFSET = 0x40050000,
	SPI_SEQ_OFFSET = 0x40060000;
#else // emulate the memory in a single file on the desktop, for the purposes of debugging, emulation etc
static const unsigned EMU_PAGESIZE = 0x1000; // 4 KiB, page size on the RP and my desktop machine
static const uint32_t SLCR_OFFSET = EMU_PAGESIZE, // 1 page in size
	CFG_OFFSET = SLCR_OFFSET + EMU_PAGESIZE, // 1 page after SLCR_OFFSET, 1 page in size
	STS_OFFSET = CFG_OFFSET + EMU_PAGESIZE, // 1 page after CFG_OFFSET, 1 page in size
	GRADIENT_MEMORY_X_OFFSET = STS_OFFSET + 2 * EMU_PAGESIZE,
	GRADIENT_MEMORY_Y_OFFSET = GRADIENT_MEMORY_X_OFFSET + 2 * EMU_PAGESIZE,
	GRADIENT_MEMORY_Z_OFFSET = GRADIENT_MEMORY_Y_OFFSET + 2 * EMU_PAGESIZE,
	GRADIENT_MEMORY_Z2_OFFSET = GRADIENT_MEMORY_Z_OFFSET + 2 * EMU_PAGESIZE,	
	RX_DATA_OFFSET = GRADIENT_MEMORY_Z2_OFFSET + 16 * EMU_PAGESIZE,
	TX_DATA_OFFSET = RX_DATA_OFFSET + 16 * EMU_PAGESIZE,
	MICRO_SEQ_MEMORY_OFFSET = TX_DATA_OFFSET + 16 * EMU_PAGESIZE,
	MICRO_SEQ_CONFIG_OFFSET = MICRO_SEQ_MEMORY_OFFSET + 16 * EMU_PAGESIZE,
	ATTEN_OFFSET = MICRO_SEQ_CONFIG_OFFSET + 16 * EMU_PAGESIZE,
	SPI_SEQ_OFFSET = ATTEN_OFFSET + 16 * EMU_PAGESIZE;
;
// Total file size needed: 107 * 4 KiB = 428 KiB
#endif

// FPGA clock frequency (HZ)
static const double FPGA_CLK_FREQ_HZ = 125e6;

// Auxiliary parameters
static const unsigned PULSE_MEM_SIZE = 32768;
static const unsigned COMMS_BUFFER = 8192;

#endif
